### PR TITLE
Upload B1 I4 plausibility

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
* Did we finalize not comparing to V1/V2? If so then `b1-i4vp-p-1003` needs to be updated
* Can you add the Q# to `full_desc` in `b1-i4vp-p-1002` just for consistency

**Review by echeng06 — DISMISSED** [review]

**Comment by jculhane** [comment]
Changing 1003 to only check against most recent visit per Janene's request

**Review by echeng06 — APPROVED** [review]

**Review by hewanadun — CHANGES_REQUESTED** [review]
@jculhane Couple of minor changes, to be consistent with how checks against UDSv3 written in other forms
- b1-i4vp-p-1003: change `short_desc` to `HEIGHT cannot differ by more than 5 inches from HEIGHT[UDSv3]`
- b1-i4vp-p-1004: change `short_desc` to `WEIGHT cannot differ by more than 50 pounds from WEIGHT[UDSv3]`
    - Remove space b/w "B1 [UDSv3]" in `comp_forms`

**Review by hewanadun — APPROVED** [review]
Looks good!

**Comment by hewanadun** [comment]
@jculhane As per Teams discussion, please update any equality checks against UDSv3. See section "Exclude Unknown or N/A codes when comparing with a previous visit" in https://github.com/naccdata/uniform-data-set/issues/210#issue-2554408480

**Pull request merged**
