### PR TITLE
FTLD - Upload E2F plausibility

### PR DESCRIPTION
**Pull request by kgauthreaux**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
Both are error 1001, please update the second to 1002

**Comment by echeng06** [comment]
Also in some columns for the second error there's a period after `FTDOTCHO`, please update to a comma

**Review by echeng06 — APPROVED** [review]
Looks good, but I wanted to also point out that the header variables are missing from the Q&V CSV (and this is referencing FRMDATEE2F). Don't know if you plan to add that in one of the existing E2F PRs or a separate one on its own. Approved otherwise!

**Comment by kgauthreaux** [comment]
@echeng06 ah it does look like they were left out. I will upload an updated var list and mc checks to the open pull request I have for those

**Pull request merged**
