### PR TITLE
Upload FTLD A3a p and revised m/c

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by echeng06 — APPROVED** [review]

**Review by echeng06 — CHANGES_REQUESTED** [review]
Please update `comp_vars` to explicitly write out all variables.

**Review by echeng06 — APPROVED** [review]

**Review by hewanadun — CHANGES_REQUESTED** [review]
@jculhane As per UDSv4 tech meeting discussion please update Q&V and error checks to add extra variables. Thanks.

**Review by echeng06 — APPROVED** [review]
Looks good to me - also I hope folks don't mind I went ahead and dealt with the merge issue, basically moved the final versions to the `forms/ftld/a3a` folder - let me know if anything looks incorrect!

**Review by hewanadun — CHANGES_REQUESTED** [review]
Since `FTDSIBBY` and `FTDCHDBY` checked against A3, do we need to make the ranges compatible?
    - In A3 SIBxYOB is `1850 to current year, or 9999`, A3a `FTDSIBBY` is `1885 – 2000`
    - In A3 KIDxYOB is `1860 to current year, or 9999`, A3a `FTDCHDBY` is  `1920 – 2000`

**Comment by jculhane** [comment]
> Since `FTDSIBBY` and `FTDCHDBY` checked against A3, do we need to make the ranges compatible? - In A3 SIBxYOB is `1850 to current year, or 9999`, A3a `FTDSIBBY` is `1885 – 2000` - In A3 KIDxYOB is `1860 to current year, or 9999`, A3a `FTDCHDBY` is `1920 – 2000`

I'm not worried about the min ages. We should update the max ages to current year, though. I've updated and will Let Laura know for REDCap.

**Review by echeng06 — APPROVED** [review]

**Pull request merged**
