### PR TITLE
UDS IVP - Upload A1a headers & new checks

### PR DESCRIPTION
**Pull request by kgauthreaux**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
* For RMMODEA1A, the PDF still only allows for 1 or 2, I just want to confirm that 1-4 is newly correct and that the PDF will be updated?
* There are also a couple misspellings of "Condtional" in the Q&V CSV, please update thanks!

M/C:
* EXPOTHER and EXPNOTAPP are missing from `a1a-ivp-m-092`

Plausibility:
* Please clean up `short_desc` (remove stuff in parentheses and mentions of the form) and also update it and `full_desc` to follow proper If/then format
    * E.g. I believe `a1a-ivp-p-1001` should say "If INRELTO is 2 and INCNTFRQ is 6 then CHILDCOMM should be <= 2", generally same idea for first 4 rules
    * Last two rules should say "then" not "and"

**Comment by hewanadun** [comment]
Check a1a-ivp-c-004 - TRSPACCESS - correct allowed values to 0,1,8

**Review by echeng06 — CHANGES_REQUESTED** [review]
M/C:
* `a1a-ivp-c-004`: TRSPACCESS should be 0,1,8 
* `a1a-ivp-c-028`: LESSMEDSYR should be 0,1,8
* `a1a-ivp-m-092`: EXPOTHER and EXPNOTAPP missing from list in `short_desc`
    * Also in `comp_vars` a comma is missing between the last 2 variables 

P:
* `a1a-ivp-p-1003`: `short_desc` needs to include "or 8"
* `a1a-ivp-p-1001 - 1004`: Need to check that MODEA2 != 0

**Comment by hewanadun** [comment]
@kgauthreaux - Need to change 117, 120 to "If MODEA1A **!= 2**, ......."

**Review by hewanadun — APPROVED** [review]
Looks good to me.
@echeng06 Please check and approve. Thanks!

**Review by echeng06 — APPROVED** [review]

**Pull request merged**
