### PR TITLE
Upload B3 I4 plausibility

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
* `b3-ivp-p-1015`: `var_name` should be TAPSLF not TAPSRT

**Comment by hewanadun** [comment]
For checks 1013 - 1018, can you update **short_desc** to the format **"If RIGIDR[UDSv3] = 1, then RIGDUPRT should not be 0"**
Similar to how A5D2 checks written https://github.com/naccdata/uniform-data-set/blob/jculhane-upload-a5d2-I4/forms/uds/a5d2/form_a5d2_i4_error_checks_p.csv

**Comment by jculhane** [comment]
Yes, we're comparing with most recent UDSv3 visit.

**Review by echeng06 — APPROVED** [review]

**Comment by hewanadun** [comment]
@jculhane A minor change,
- In b3-i4vp-p-1008, update where it says "and/or" in descriptions to "or".
No need to create a new branch specifically for this one, note it down to do in a final pass or submit it with another form (let us know in the comments if you do that).

**Pull request merged**
