### PR TITLE
UDS IVP - Uploading A1 requested changes

### PR DESCRIPTION
**Pull request by kgauthreaux**
Uploading requested changes plus updated var list for an "ADMIN" variable (will only be on A1 and A1a) and new checks associated with that

### CODE REVIEW

**Comment by echeng06** [comment]
@kgauthreaux For `a1-ivp-p-1007`, we weren't sure if it made more sense to put this under FRMDATEA1 instead of BIRTHYR - what do you guys think? Also I think needs to be under FRMDATEA1 instead of FRMDATEB9 - either way it also needs to be added to `comp_vars`.

**Review by hewanadun — CHANGES_REQUESTED** [review]
@kgauthreaux 
I added a new section to https://github.com/naccdata/uniform-data-set/issues/210#issue-2554408480. Please check **"Cross form error checks involving optional forms"** and make the necessary changes.

**Review by echeng06 — CHANGES_REQUESTED** [review]
Q&V:
* For consistency let's update everywhere under `conformity` that says "1 or blank" to "Integer 1 or blank"

MC:
* `a1-ivp-m-152 - 159`: `comp_vars` is missing for header field-related rules 
* `a1-ivp-c-147`: Please update columns to use `/` instead of `-` in dates

Plausibility: 
* `a1-ivp-p-1008`: Don't know if we want to make this a bit of a tighter restriction and say "If MARISTAT is 2,5" (2 is widowed)? I think we can still leave out 3,4 though.

**Comment by hewanadun** [comment]
- a1-ivp-p-1012 `test_logic` incorrect

**Comment by hewanadun** [comment]
@kgauthreaux this is not fixed yet
> * a1-ivp-p-1012 `test_logic` incorrect

**Comment by kgauthreaux** [comment]
@hewanadun oops sorry I missed your comment!

**Review by hewanadun — APPROVED** [review]

**Review by echeng06 — APPROVED** [review]

**Pull request merged**
