### PR TITLE
LBD - Upload v3 E3L var list and m/c

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
Has same concerns as E2L: https://github.com/naccdata/uniform-data-set/pull/260#pullrequestreview-2417088250

Mainly Q&V issues  and all the "if X is 0 or Y is 0 or Z is 1-3 then" rules can be simplified. I don't think it's as complicated as E2F though since it doesn't have all the subquestion skipping.

**Review by echeng06 — CHANGES_REQUESTED** [review]
* `e3l-lbdivp-c-089`: Can be 0,1, 8, or 9
* "LBOANAVL" is misspelled as "LBOAVL" for all instances

**Comment by hewanadun** [comment]
@jculhane 
- Same as E2L - In Q&V, for the variables that can be blank, please update the conformity column.
- Looks like `error_no` column got reset again, can remove this column if not useful (https://github.com/naccdata/uniform-data-set/pull/260#issuecomment-2470705138)

**Review by echeng06 — APPROVED** [review]

**Comment by echeng06** [comment]
Approved assuming Chandima's additional change requests

**Review by hewanadun — APPROVED** [review]

**Pull request merged**
