### PR TITLE
Upload C2T form, variable checklist, and m/c checks

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
Q&V CSV
* `MODEC2C2T` can only be 2
* `RMREASC2C2T` and `RMMODEC2C2T` missingness should be "Always"

Error checks CSV
* Please make error codes lowercase for consistency
* `c2t-ivp-m-166/168`: `CERADJ7YES` (9d) should be dependent on `CERAD1REC` (7a) not `CERADJ6REC` (9b) 
* `c2t-ivp-m-169/171`: `CERADJ7NO` (9e) should be dependent on `CERADJ7YES` (9d)
* `c2t-ivp-m-171`: missing "If" in `short_desc`
* `c2t-ivp-c-258`: should result in `MOCBTOTS` not `MOCATOTS`

**Review by echeng06 — CHANGES_REQUESTED** [review]
* Minor thing but please clean up `short_desc` for `c2t-ivp-m-171` (Remove `Q9d.` and stuff in parentheses)
* It looks like `MOCBTOTS` was changed to `MOCATOTS` in the Q&V but was left as `MOCBTOTS` in the error checks, I'm guessing this also needs to be updated to `MOCATOTS`? Or which is it?
    * @hewanadun also asked for C2 and C2T to be merged (on our side) so it would make sense to have them be the same, but there are some other inconsistencies on the headers (e.g. `MODEC2C2T` only being 2 on C2T but can be 1 or 2 on C2) - tagging for her input as I'm not familiar with how this should be done

**Comment by hewanadun** [comment]
@jculhane @kgauthreaux  Regarding Emily's question about MODEC2C2T, in REDCap C2C2T is a single form and there's only one variable MODEC2C2T with allowed values 1 - in person, 2 - remote. From previous discussions, I thought in PDF forms, C2 is the in person option and C2T is the remote option and for a given visit they can only submit either C2 or C2T, and using MODEC2C2T we can identify which form is submitted. But it seems C2 PDF has remote option too, if that's the case we need some other way to identify which form is submitted.

**Comment by hewanadun** [comment]
@jculhane based on our Teams discussion we'll do the following

- If RMMODEC2C2T = 1 => validate as C2T submission.
- If RMMODEC2C2T = Any other value or blank => validate as C2 submission. 
(Note that if centers enter wrong RMMODEC2C2T value for C2T it'll be validated as a C2 submission)

RT needs to add following checks to prevent C2 only variables present in C2T, and vice versa.
- In C2, add a plausibility check for extra C2T variables
    - If RMMODEC2C2T=2 or blank, then [list of vars present only in C2T] must be blank
- In C2T, add a plausibility check for extra C2 variables
    - If RMMODEC2C2T=1 then [list of vars present only in C2] must be blank

**Review by echeng06 — CHANGES_REQUESTED** [review]
Plausibility: 
* `c2t-ivp-p-1001-1004`: Please update short_desc and full_desc to follow the follow a "If X is ... then Y must be ..." format and so that var_name is the _resulting_ variable (re: #210) 
* `c2t-ivp-p-1006`: Can you update short_desc to also say that UDSVERFC and UDSVERLC must not be 95-98?

**Review by echeng06 — CHANGES_REQUESTED** [review]
Plausibility changes look good, sorry also just noticed in the Q&V CSV that the response label for `MOCALAN`, `MOCALANX`, and `MOCAHEAR` is incorrect (kinda looks like they got shifted).

**Review by echeng06 — APPROVED** [review]

**Comment by hewanadun** [comment]
@jculhane apologies for requesting these changes after the PR is closed, please create a new branch.

- Does MOCALAN need another plausibility check for 1,3 (If MOCALAN is 1,3 then LANGC2C2T should not = 2)?
- Similarly, does NPSYLAN need another plausibility check for 1,3 (If NPSYLAN is 1,3 then LANGC2C2T should not = 2)?
- Please double check the allowed values, there are several places that say "must be between 0 and 77 or 95 and 98", which should be corrected to "must be between 0 and 77 or between 95 and 98"
- For c2t-ivp-p-1007 and c2t-ivp-p-1008, can you update these checks to sum to be computed only if subquestions are filled?

**Comment by echeng06** [comment]
Also in `c2t-ivp-p-1007`, `UDSVERFN` is misspelled in `comp_vars` (missing s).

**Pull request merged**
