### PR TITLE
Add files via upload - A5D2 m/c and p checks

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
Questions and vars:

- `FRMDATEA5D2` should specify conformity to be both `mm/dd/yyyy` and `yyyy/mm/dd`

Errors MC - general

- `SEIZNUM` with error `a5d2-ivp-m-113` and `a5d2-ivp-m-114`, based on the PDF it sounds like it should only be filled if `SEIZURES` is 1 (recent/active), and blank if all else (0 (absent), 2 (remote/inactive), 9 (unknown))
- `CPAP` and `APNEAORAL` same as the above in response to `APNEA`
- `DIABTYPE` error `a5d2-ivp-m-160` should be "If DIABETES is 1 or 2", not just 1
- `DIABAGE` error `a5d2-ivp-m-170` same as above
- `OTHSLEEX` error `a5d2-ivp-c-218` same as above in response to `OTHSLEEP` , and is also missing the inverse rule (if 0,9 then must be blank)
- `OTHCONDX` error `a5d2-ivp-m-278` same as above in response to `OTHERCOND`, and is also missing the inverse rule (if 0, 9 then must be blank)
- `DEPRTREAT` errors `a5d2-ivp-m-283` and `a5d2-ivp-m-284` should only be present if active (1) instead of 1 and 2
- All the 7c subvariables have the `test_logic` column reference not 9, which can probably be removed (errors `a5d2-ivp-c-317` - `a5d2-ivp-c-325`)

Error MC - I believe a lot of rules are missing their inverse, but let me know if that is incorrect. Otherwise:

- `OTHSLEEX` and `OTHCONDX` as mentioned above
- `IMPOTHERX` needs another inverse rule specifying "If `IMPOTHER` is blank then `IMPOTHERX` must be blank" (opposite of `a5d2-ivp-m-136`)
- `ARTHTYPX` in response to `ARTHROTHR` (opposite of `a5d2-ivp-c-192`)
- `CANCOTHERX` in response to `CANCOTHER` (inverse of `a5d2-ivp-c-234`)
- `CANCERPRIM`, `CANCMETBR` , `CANCBLOOD` , `CANCRAD` in response to `CANCERACTV` (opposites of `a5d2-ivp-m-226`, `a5d2-ivp-m-227`, `a5d2-ivp-m-235`, `a5d2-ivp-m-245`)
- `CANCMETBR` in response to `CANCERMETA` (opposite of `a5d2-ivp-m-227`)
- `IMPAMFOOT` in response to `HEADIMP` (opposite of `a5d2-ivp-m-137`)
- `DIABINS` in response to `DIABETES` (opposite of `a5d2-ivp-m-169`)
- `ARTHRRHEUM`, `ARTHUPEX` in response to `ARTHRIT` (opposite of `a5d2-ivp-m-194`, `a5d2-ivp-m-199`)
- `OTHANXDISX` in response to `OTHANXDIS` (opposite of `a5d2-ivp-m-304`)
- `PSYCDISX` in response to `PSYCDIS` (opposite of `a5d2-ivp-m-311`)
- `NOMENSOTHX` in response to `NOMENSOTH` (opposite of `a5d2-ivp-m-326`)
- `NOMENSNAT` in response to `NOMENSAGE` (opposite of `a5d2-ivp-m-327`) 

Error MC/Question and Vars - incompatible rules

- `MENARCHE` with error code `a5d2-ivp-m-312` refers to `SEX` but that does not appear on the form - may need to be changed to a plausibility check and reference a different form
- PDF is in conflict with `HRT` (7d) - PDF implies this is not dependent on anything (7a and 7b), but errors `a5d2-ivp-m-328` and `a5d2-ivp-m-329` are reliant on `MENARCHE` - these two likely need to be removed/replaced with a plausibility check same as above
- `BCPILLS` same situation as above for `a5d2-ivp-m-340` and `a5d2-ivp-m-341`

**Comment by jculhane** [comment]
I've made all changes except the ones for HRT and BCPILLS - These should be filled out if Q7 is filled out, and should be blank if Q7 is blank. These error checks are more stringent than the alert for Q7 (comparing against BIRTHSEX).

**Review by hewanadun — CHANGES_REQUESTED** [review]
@jculhane 
Please check issue https://github.com/naccdata/uniform-data-set/issues/210 and fix A5D2 checks accordingly. Thanks.

**Comment by echeng06** [comment]
@jculhane @hewanadun The changes in regards to #210 causes some overlapping rules which need to be combined, e.g. (ARTHRIT: `a5d2-ivp-m-356`, `a5d2-ivp-m-357`) and (CANCERACTV: `a5d2-ivp-m-359`, `a5d2-ivp-m-362`, `a5d2-ivp-m-363`), possibly others

**Review by hewanadun — DISMISSED** [review]
Looks good

**Review by echeng06 — CHANGES_REQUESTED** [review]
Plausibility rules:

* `a5d2-ivp-p-1001` should be BIRTHSEX=2 (female), not 1 (male) for several columns
    * Should also be reworded to say "then MENARCHE cannot be blank"? 
* `a5d2-ivp-p-1003` has some typos of ALCDRINKS (missing C, ALDRINKS)
    * Kind of a technicality I don't know how to resolve without changing the PDF. For `ALCDRINKS` they could pick 4 (5-6 drinks) meaning specifically 5 drinks, and want to select 0 (never) for `ALCBINGE` since it's **6 or more** drinks
* `a5d2-ivp-p-1007: Rule needs to be rewritten with swapped logic so that `RBD` is the `var_name`, else moved to B9  
* `a5d2-ivp-p-1020` has typo, should be `OTHANXD` not `OTHAND`

**Comment by jculhane** [comment]
> * `a5d2-ivp-p-1001` - Should also be reworded to say "then MENARCHE cannot be blank"?
We're not absolutely requiring responses to these questions if BIRTHSEX=F (e.g. could be distressing for trans men)
> * `a5d2-ivp-p-1003` - This is a technicality I don't know how to resolve without changing the PDF/variable. But for `ALCDRINKS` they could pick 4 (5-6 drinks) meaning specifically 5 drinks, and want to select 0 (never) for `ALCBINGE` since it's **6 or more** drinks
OK if we don't check for this.

**Review by echeng06 — DISMISSED** [review]
Looks good!

**Review by hewanadun — DISMISSED** [review]

**Comment by echeng06** [comment]
@jculhane do you mind removing the I4, merging this branch, and then starting a new PR for the I4? It'll just be easier to keep things separate.

**Review by echeng06 — APPROVED** [review]

**Pull request merged**
