### PR TITLE
LBD - Upload v3 B9L missingness & conformity

### PR DESCRIPTION
**Pull request by kgauthreaux**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
* `b9l-lbdivp-c-008`: `short_desc` needs to say 1-7, not 1-3
* `b9l-lbdivp-c-016`: `short_desc` should say "SCCOFRST must be 1, 2, or 8"
* Please fill out `comp_vars` column

**Review by hewanadun — CHANGES_REQUESTED** [review]
- For checks 003 - 014, it seems `blank` is an accepted value. Please update the Q&V CSV and m/c checks to reflect this.
- Fix check 029 => `If SCCOSCVR is in (1,2), SCCOTH **must be** blank`

**Comment by echeng06** [comment]
For 029, it's also possible for SCCOSCVR to be blank, so I think the rule should change to "If SCCOSCVR is not 3 then SCCOTH must be blank"

**Comment by kgauthreaux** [comment]
@echeng06 @hewanadun I made all requested edits expect the comment "For checks 003 - 014, it seems blank is an accepted value. Please update the Q&V CSV and m/c checks to reflect this." the variable list already states that these variables are not required and there are no missingness checks for these

**Comment by hewanadun** [comment]
> @echeng06 @hewanadun I made all requested edits expect the comment "For checks 003 - 014, it seems blank is an accepted value. Please update the Q&V CSV and m/c checks to reflect this." the variable list already states that these variables are not required and there are no missingness checks for these

@kgauthreaux I think I requested above after seeing C2F checks, where blanks are specifically mentioned in `conformity`. 
- https://github.com/naccdata/uniform-data-set/blob/jculhane-upload-ftld-c2f/forms/ftld/form_c2f_ivp_questions_and_vars.csv
- https://github.com/naccdata/uniform-data-set/blob/jculhane-upload-ftld-c2f/forms/ftld/form_c2f_ivp_error_checks_mc.csv

But that might be due to the fact that entire C2F can be left blank in some circumstances. If you think that level of detail not required for B9L we can leave it as it is.

**Review by hewanadun — APPROVED** [review]

**Comment by hewanadun** [comment]
@echeng06 Please approve. Thanks!

**Review by echeng06 — APPROVED** [review]

**Pull request merged**
