### PR TITLE
Upload revised A4 var list and m/c to reflect allowed 0s

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by hewanadun — CHANGES_REQUESTED** [review]
@jculhane
In Q&V csv, I think `branching_logic` needs to be filled for all RXNORMID columns?

**Comment by hewanadun** [comment]
@echeng06 FYI - We don't need rule definition updates for this change, allowing 0 is already handled in rxcui validation.

**Comment by jculhane** [comment]
> @echeng06 FYI - We don't need rule definition updates for this change, allowing 0 is already handled in rxcui validation.

@hewanadun Sorry - do we need the 0 change in the CSVs, or should I close this pull request and just upload a var list w/ branching logic?

**Comment by hewanadun** [comment]
> > @echeng06 FYI - We don't need rule definition updates for this change, allowing 0 is already handled in rxcui validation.
> 
> @hewanadun Sorry - do we need the 0 change in the CSVs, or should I close this pull request and just upload a var list w/ branching logic?

@jculhane we need the m/c CSV updates, I was just letting Emily know the validation code is already updated to allow 0, so no new changes required form our side. Sorry for the confusion.

**Review by hewanadun — APPROVED** [review]
Looks good!

**Pull request merged**
