### PR TITLE
UDS - Upload B8 I4 plausibility

### PR DESCRIPTION
**Pull request by kgauthreaux**

### CODE REVIEW

**Review by echeng06 — CHANGES_REQUESTED** [review]
* `b8-i4vp-p-1022`: `var_name` should only be under NORMNREXAM
* `b8-i4vp-p-1024`: `var_name` should only be under GAITFIND

**Comment by kgauthreaux** [comment]
@echeng06 oops sorry didn't see those!

**Review by echeng06 — DISMISSED** [review]

**Review by hewanadun — CHANGES_REQUESTED** [review]
Similar to IVP (https://github.com/naccdata/uniform-data-set/pull/207#pullrequestreview-2439822710), duplicate checks b/w B3 I4 and B8 I4 need to be removed.

**Review by hewanadun — APPROVED** [review]
@echeng06 Please update the rule definitions.

**Pull request merged**
