### PR TITLE
Upload B1 form and plausibility checks

### PR DESCRIPTION
**Pull request by jculhane**

### CODE REVIEW

**Review by hewanadun — CHANGES_REQUESTED** [review]
@jculhane 

When referring to variables and form names, 

- Let's include the version only if it's not the current version. 
- Include the version within brackets after the variable name or form name
- List current version variables/forms first in comp_vars/comp_forms

For example
- In b1-i4vp-p-1003, comp_forms => B1, B1(UDSv3)
- In b1-i4vp-p-1004, test_logic => IF |WEIGHT - WEIGHT(UDSv3)| > 50

In b1-i4vp-p-1004, what does it mean by "If WEIGHT changes by more than 50 pounds from UDSv3"? Does it mean the most recent UDSv3 visit or across all UDSv3 visits as in check b1-i4vp-p-1003? Please update the error check to clarify this.

**Comment by jculhane** [comment]
Thanks @hewanadun . Please let me know how the edits look. For b1-i4vp-p-1004, we're only comparing the current visit weight to the most recent prior visit (whether that was in v1, v2, v3, or v4). Hopefully the edits make that clear.

**Comment by hewanadun** [comment]
@jculhane. Checks look good now. RT can go ahead and write the rest of the I4 plausibility checks in the same format. I'm keeping this PR open as TT need to add new functionality to support these rule definitions. Will close this once we are done. Thanks!

**Comment by echeng06** [comment]
Could we reword the descriptions so that it's "VAR1 and VAR2 cannot differ by more than X", just so it's not an incomplete if clause? `b1-i4vp-p-1003` for example kind of does it that way.

**Review by echeng06 — CHANGES_REQUESTED** [review]
Could we reword the descriptions so that it's "VAR1 and VAR2 cannot differ by more than X", just so it's not an incomplete if clause? `b1-i4vp-p-1003` for example kind of does it that way. Also shouldn't `var_name` only be under one variable?

**Comment by hewanadun** [comment]
@jculhane 
In b1-ivp-p-1001 change **var_name** column to only have WAIST1
In b1-ivp-p-1002 change **var_name** column to only have HIP1

Also could you please delete I4 plausibility checks from here and open a new PR for that in a separate branch. Thanks!

**Review by hewanadun — APPROVED** [review]

**Comment by hewanadun** [comment]
@jculhane just noticed that MODEB1 is not updated to new values

- In Q&V needs to update MODEB1 to new values
- Update m/c checks to use new values for MODEB1

**Comment by hewanadun** [comment]
@jculhane check b1-ivp-m-040 also need to be updated to new value

**Review by hewanadun — APPROVED** [review]
Looks good now!
@echeng06 please update both IVP and I4 rule definitions

**Comment by echeng06** [comment]
@jculhane Does B1 also need this same 94 to 92 change? https://github.com/naccdata/uniform-data-set/pull/249

**Comment by jculhane** [comment]
> @jculhane Does B1 also need this same 94 to 92 change? #249
> 
> I also see it in B3

No, we just wanted the definition of 94=Remote to stay consistent across forms. Since it meant something different in A2, we needed to change it there.

**Review by echeng06 — APPROVED** [review]

**Comment by jculhane** [comment]
@echeng06 @hewanadun Apologies - it says this branch has conflicts that must be resolved before I can merge. I'm not sure how to resolve conflicts (or how they appeared).

**Review by hewanadun — APPROVED** [review]
@jculhane There were some weird characters in the cvs headers in main branch, and in this branch leading zeros were missing in `error_no` column. I fixed those. 
Please double check the m/c, q&V files and merge.

**Pull request merged**
